# Generated by Django 6.0.1 on 2026-01-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarineAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('height', models.FloatField(help_text='Taille en mètres')),
                ('species', models.CharField(max_length=255)),
                ('thumb', models.ImageField(blank=True, upload_to='medias/%Y/%m')),
                ('cover', models.ImageField(blank=True, upload_to='medias/%Y/%m')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiplouf.category')),
                ('tags', models.ManyToManyField(to='wikiplouf.tag')),
            ],
        ),
    ]
